# windows/action.yaml
name: Install Senzing API - windows
description: Install Senzing API on the windows platform.
author: support@senzing.com

inputs:
  senzingapi-version:
    description: Version of Senzing API to install
    required: true

runs:
  using: composite
  steps:
    # Install latest staging or production image.

    - env:
        SENZING_INSTALL_VERSION: ${{ inputs.senzingapi-version }}
      name: Install Senzing API
      shell: bash
      run: $GITHUB_ACTION_PATH/install-senzing.sh

branding:
  icon: download
  color: green
