# install-senzing.yaml
name: Install Senzing - windows
description: Install Senzing API on the windows platform.
author: support@senzing.com

runs:
  using: composite
  steps:
    - name: Install Senzing API
      shell: cmd
      run: |
        curl --output senzingapi.zip https://public-read-access.s3.amazonaws.com/staging/SenzingAPI_3.7.0.zip
    - name: Unzip
      shell: cmd
      run: |
        7z x -y -o"C:\Program Files" senzingapi.zip
    - name: Rename help
      shell: cmd
      run: |
        ren /h
    - name: Rename 1
      shell: cmd
      run: ren "C:\Program Files\senzing" "C:\Program Files\senzing2" && ren "C:\Program Files\senzing2" "C:\Program Files\Senzing"
    - name: Rename 2
      shell: cmd
      run: |
        ren "C:\Program Files\senzing2" "C:\Program Files\Senzing"
    - name: Dir 1
      shell: cmd
      run: |
        dir "C:\Program Files\Senzing"
    - name: Dir 2
      shell: cmd
      run: |
        dir "C:\Program Files\Senzing\g2"

branding:
  icon: download
  color: green
