# windows/action.yaml
name: Install Senzing - windows
description: Install Senzing API on the windows platform.
author: support@senzing.com

inputs:
  senzingapi-version:
    description: Version of Senzing API to install
    required: false
    default: latest

runs:
  using: composite
  steps:
    # Download staging, latest, or versioned image.

    - if: inputs.senzingapi-version == 'staging'
      env:
        SENZINGAPI_STAGING_URL: https://public-read-access.s3.amazonaws.com/staging/SenzingAPI_staging.zip
      name: Download staging Senzing API
      shell: cmd
      run: curl --output senzingapi.zip %SENZINGAPI_STAGING_URL%

    - if: inputs.senzingapi-version == 'latest'
      env:
        SENZINGAPI_LATEST_URL: https://public-read-access.s3.amazonaws.com/staging/SenzingAPI_latest.zip
      name: Download Senzing API
      shell: cmd
      run: curl --output senzingapi.zip %SENZINGAPI_LATEST_URL%

    - if: ${{ inputs.senzingapi-version != 'latest' && inputs.senzingapi-version != 'staging' }}
      env:
        SENZINGAPI_LATEST_URL: https://public-read-access.s3.amazonaws.com/staging/SenzingAPI_latest.zip
      name: Download versioned Senzing API
      shell: cmd
      run: curl --output senzingapi.zip %SENZINGAPI_LATEST_URL%

    # Install Senzing API.

    - name: Install Senzing API
      shell: cmd
      run: |
        7z x -y -o"C:\Program Files" senzingapi.zip
        ren "C:\Program Files\senzing" "senzing2"
        ren "C:\Program Files\senzing2" "Senzing"

    # Verify installation.

    - name: Verify installed Senzing API version
      shell: bash
      run: cat "/c/Program Files\senzing\g2\g2BuildVersion.json"

branding:
  icon: download
  color: green
