# windows/action.yaml
name: Install Senzing - windows
description: Install Senzing API on the windows platform.
author: support@senzing.com

inputs:
  senzingapi-version:
    description: Version of Senzing API to install
    required: true

runs:
  using: composite
  steps:

    # Download latest staging or production image.

    - env:
        SENZING_INSTALL_VERSION: ${{ inputs.senzingapi-version }}
      name: Install Senzing API
      shell: bash
      run: ${{ github.action_path }}/windows/download-senzing.sh

    # Install Senzing API.

    - name: Install Senzing API
      shell: cmd
      run: |
        7z x -y -o"C:\Program Files" senzingapi.zip
        ren "C:\Program Files\senzing" "senzing2"
        ren "C:\Program Files\senzing2" "Senzing"

    # Verify installation.

    - name: Verify installed Senzing API version
      shell: bash
      run: cat "/c/Program Files\senzing\g2\g2BuildVersion.json"

branding:
  icon: download
  color: green
