# install-senzing.yaml
name: Install Senzing - windows
description: Install Senzing API on the windows platform.
author: support@senzing.com

runs:
  using: composite
  steps:
    - name: Platform identification
      run: echo "Running windows/action.yaml"
      shell: bash

branding:
  icon: download
  color: green
