name: Install Senzing API Runtime
description: Install Senzing API Runtime based on platform.
author: support@senzing.com

inputs:
  package(s)-to-install:
    description: Space separated list of Senzing packages to install. Linux only.
    default: "senzingapi-runtime"
  senzingapi-version:
    description: Version of Senzing API to install
    default: "production-v3"

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      name: Run on Linux
      uses: senzing-factory/github-action-install-senzing-api/linux@v3
      with:
        senzingapi-version: ${{ inputs.senzingapi-version }}
        package(s)-to-install: ${{ inputs.package(s)-to-install }}

    - if: runner.os == 'macOS'
      name: Run on macOS
      uses: senzing-factory/github-action-install-senzing-api/darwin@v3
      with:
        senzingapi-version: ${{ inputs.senzingapi-version }}

    - if: runner.os == 'Windows'
      name: Run on Windows
      uses: senzing-factory/github-action-install-senzing-api/windows@v3
      with:
        senzingapi-version: ${{ inputs.senzingapi-version }}

branding:
  icon: download
  color: green
