name: Install Senzing API
description: Install Senzing API based on platform.
author: support@senzing.com

inputs:
  senzingapi-version:
    description: Version of Senzing API to install
    required: true

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      name: Run on Linux
      uses: senzing-factory/github-action-install-senzing/linux@"#52-skern"
      with:
        senzingapi-version: ${{ inputs.senzingapi-version }}

    - if: runner.os == 'macOS'
      name: Run on macOS
      uses: senzing-factory/github-action-install-senzing/darwin@"#52-skern"
      with:
        senzingapi-version: ${{ inputs.senzingapi-version }}

    - if: runner.os == 'Windows'
      name: Run on Windows
      uses: senzing-factory/github-action-install-senzing/windows@"#52-skern"
      with:
        senzingapi-version: ${{ inputs.senzingapi-version }}

branding:
  icon: download
  color: green
