name: Install Senzing API Runtime
description: Install Senzing API Runtime based on platform.
author: support@senzing.com

inputs:
  senzingapi-runtime-version:
    description: Version of Senzing API to install
    required: true

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      name: Run on Linux
      uses: senzing-factory/github-action-install-senzing-api/linux@59-skern
      with:
        senzingapi-runtime-version: ${{ inputs.senzingapi-runtime-version }}

    - if: runner.os == 'macOS'
      name: Run on macOS
      uses: senzing-factory/github-action-install-senzing-api/darwin@v2
      with:
        senzingapi-version: ${{ inputs.senzingapi-version }}

    - if: runner.os == 'Windows'
      name: Run on Windows
      uses: senzing-factory/github-action-install-senzing-api/windows@v2
      with:
        senzingapi-version: ${{ inputs.senzingapi-version }}

branding:
  icon: download
  color: green
