# action.yml
name: Install Senzing
description: Install Senzing API based on platform.
author: support@senzing.com

inputs:
  senzingapi-version:
    description: Version of Senzing API to install
    required: false
    default: latest

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      name: Run on Linux
      uses: Senzing/github-action-install-senzing/linux@main
      with:
        senzingapi-version: ${{ inputs.senzingapi-version }}
    - if: runner.os == 'macOS'
      name: Run on macOS
      uses: Senzing/github-action-install-senzing/darwin@main
      with:
        senzingapi-version: ${{ inputs.senzingapi-version }}
    - if: runner.os == 'Windows'
      name: Run on Windows
      uses: Senzing/github-action-install-senzing/windows@main
      with:
        senzingapi-version: ${{ inputs.senzingapi-version }}

branding:
  icon: download
  color: green
