# action.yml
name: Install Senzing
description: Install Senzing API based on platform.
author: support@senzing.com

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      name: Run on Linux
      uses: Senzing/github-action-install-senzing/linux@main
    - if: runner.os == 'macOS'
      name: Run on macOS
      uses: Senzing/github-action-install-senzing/darwin@main
    - if: runner.os == 'Windows'
      name: Run on Windows
      uses: Senzing/github-action-install-senzing/windows@main

branding:
  icon: download
  color: green
