# darwin/action.yaml
name: Install Senzing - darwin
description: Install Senzing API on the darwin/macOS platform.
author: support@senzing.com

inputs:
  senzingapi-version:
    description: Version of Senzing API to install
    required: false
    default: latest

runs:
  using: composite
  steps:
    # Download staging, latest, or versioned image.

    - if: inputs.senzingapi-version == 'staging'
      env:
        SENZINGAPI_STAGING_URL: https://public-read-access.s3.amazonaws.com/staging/Senzing_staging.dmg
      name: Download staging Senzing API
      shell: bash
      run: curl --output /tmp/senzingapi.dmg $SENZINGAPI_STAGING_URL

    - if: inputs.senzingapi-version == 'latest'
      env:
        SENZINGAPI_LATEST_URL: https://public-read-access.s3.amazonaws.com/staging/Senzing_latest.dmg
      name: Download Senzing API
      shell: bash
      run: curl --output /tmp/senzingapi.dmg $SENZINGAPI_LATEST_URL

    - if: ${{ inputs.senzingapi-version != 'latest' && inputs.senzingapi-version != 'staging' }}
      env:
        SENZINGAPI_LATEST_URL: https://public-read-access.s3.amazonaws.com/staging/Senzing_latest.dmg
      name: Download versioned Senzing API
      shell: bash
      run: curl --output /tmp/senzingapi.dmg $SENZINGAPI_LATEST_URL

    # Install Senzing API.

    - name: Install Senzing API
      shell: bash
      run: |
        hdiutil attach /tmp/senzingapi.dmg
        sudo mkdir -p /opt/senzing/
        sudo cp -R /Volumes/SenzingAPI/senzing/g2 /opt/senzing

    # Verify installation.

    - name: Verify installed Senzing API version
      shell: bash
      run: cat /opt/senzing/g2/g2BuildVersion.json

branding:
  icon: download
  color: green
