name: Install Senzing API - darwin
description: Install Senzing API on the darwin/macOS platform.
author: support@senzing.com

inputs:
  senzingapi-version:
    description: Version of Senzing API to install
    required: true

runs:
  using: composite
  steps:
    # Install latest staging or production image.

    - env:
        SENZING_INSTALL_VERSION: ${{ inputs.senzingapi-version }}
      name: Install Senzing API
      shell: bash
      run: ${{ github.action_path }}/install-senzing.sh

branding:
  icon: download
  color: green
