name: Install Senzing - linux
description: Install Senzing API on the linux platform.
author: support@senzing.com

inputs:
  senzingapi-version:
    description: Version of Senzing API to install
    required: false
    default: latest

runs:
  using: composite
  steps:

    # Install staging, production or versioned release.

    - env:
        SENZING_ACCEPT_EULA: I_ACCEPT_THE_SENZING_EULA
        SENZING_INSTALL_VERSION: ${{ inputs.senzingapi-version }}
      name: Install Senzing API
      shell: bash
      run: ${{ github.action_path }}/install-senzing.sh

    # Adjust files for "system install".

    - name: Configure Senzing API
      shell: bash
      run: |
        sudo mv /opt/senzing/data/4.0.0/* /opt/senzing/data/
        sudo mkdir /etc/opt/senzing
        sudo cp /opt/senzing/g2/resources/templates/cfgVariant.json     /etc/opt/senzing
        sudo cp /opt/senzing/g2/resources/templates/customGn.txt        /etc/opt/senzing
        sudo cp /opt/senzing/g2/resources/templates/customOn.txt        /etc/opt/senzing
        sudo cp /opt/senzing/g2/resources/templates/customSn.txt        /etc/opt/senzing
        sudo cp /opt/senzing/g2/resources/templates/defaultGNRCP.config /etc/opt/senzing
        sudo cp /opt/senzing/g2/resources/templates/stb.config          /etc/opt/senzing

    # Verify installation.

    - name: Verify installed Senzing API version
      shell: bash
      run: cat /opt/senzing/g2/g2BuildVersion.json

branding:
  icon: download
  color: green
