name: Install Senzing API Runtime - linux
description: Install Senzing API Runtime on the linux platform.
author: support@senzing.com

inputs:
  senzingapi-runtime-version:
    description: Version of Senzing API Runtime to install
    required: true

runs:
  using: composite
  steps:

    # Install staging, production or versioned release.

    - env:
        SENZING_ACCEPT_EULA: I_ACCEPT_THE_SENZING_EULA
        SENZING_INSTALL_VERSION: ${{ inputs.senzingapi-runtime-version }}
      name: Install Senzing API Runtime
      shell: bash
      run: ${{ github.action_path }}/install-senzing.sh

branding:
  icon: download
  color: green
