name: make latest tag

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  make-go-tag:
    name: make a vM.m.P tag
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run latest-tag
        uses: EndBug/latest-tag@v1
